runtime: nodejs16
handlers:
  
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    secure: always
    static_files: build/index.html
    upload: build/index.html

# The above code tells Google Cloud to upload all the contents inside the build folder
# and point any incoming request at the root to build/index.html.
 
